import Phaser from 'phaser';
import { venueRegistry } from '../venueRegistry.js';
import { DISTRICT_PROPS, INTERIOR_PROPS, EMOTE_FRAMES } from '../assets.generated.js';
import { UI, UI_HEX } from '../palette.js';
import { tr } from '../../i18n/index.js';
import {
  ANIMATED_OBJECTS,
  AVATAR_VARIANTS,
  DIRECTION_ORDER,
  EMOTES,
  animKey,
  animStartFrame,
  sitFrames,
  sleepFrames,
} from '../assetManifest.js';
import { resolvedAnimDef } from '../agents/AppearanceResolver.js';

const ANIM_RATE = { idle: 5, walk: 10, sit: 4, sleep: 3 } as const;

export class PreloaderScene extends Phaser.Scene {
  constructor() { super({ key: 'PreloaderScene' }); }

  preload() {
    const { width, height } = this.scale;

    // Loading UI — TZ-06 palette (matte graphite + coral progress bar)
    this.add.rectangle(width / 2, height / 2, 280, 12, UI_HEX.ink900).setStrokeStyle(1, 0x3a352c);
    const bar = this.add.rectangle(width / 2 - 140, height / 2, 0, 10, UI_HEX.accentCoral).setOrigin(0, 0.5);
    this.add.text(width / 2, height / 2 - 28, 'BotVille', {
      fontSize: '18px', color: UI.textOnDark, fontFamily: 'monospace', letterSpacing: 4,
    }).setOrigin(0.5);
    const status = this.add.text(width / 2, height / 2 + 22, tr('game.initializing'), {
      fontSize: '10px', color: UI.textOnDarkMuted, fontFamily: 'monospace',
    }).setOrigin(0.5);

    this.load.on('progress', (v: number) => {
      bar.width = 280 * v;
      status.setText(tr('game.loading', { pct: Math.round(v * 100) }));
    });

    // Maps and atlases for every venue (generated by scripts/world-bake.mjs)
    for (const v of venueRegistry.all()) {
      this.load.tilemapTiledJSON(v.id, `assets/tilemaps/${v.id}.tmj`);
    }
    for (const atlasId of new Set(venueRegistry.all().map(v => v.groundAtlas))) {
      this.load.image(atlasId, `assets/tilesets/pack/${atlasId}.png`);
    }

    // Props: name = texture key = file name
    for (const key of DISTRICT_PROPS) this.load.image(key, `assets/sprites/pack/district/${key}.png`);
    for (const key of INTERIOR_PROPS) this.load.image(key, `assets/sprites/pack/interior/${key}.png`);

    // Agent spritesheets (humans + animals) — frame sizes come from the manifest
    for (const v of AVATAR_VARIANTS) {
      this.load.spritesheet(v.textureKey, v.file, {
        frameWidth: v.frameWidth,
        frameHeight: v.frameHeight,
      });
    }

    for (const [key, def] of Object.entries(ANIMATED_OBJECTS)) {
      this.load.spritesheet(`anim-${key}`, def.file, {
        frameWidth: def.frameWidth,
        frameHeight: def.frameHeight,
      });
    }

    // Emotes: one file, two slicings (16x32 bubble and 16x16 icons)
    this.load.spritesheet(EMOTES.think.textureKey, EMOTES.file, {
      frameWidth: EMOTES.think.frameWidth,
      frameHeight: EMOTES.think.frameHeight,
    });
    this.load.spritesheet(EMOTES.icons.textureKey, EMOTES.file, {
      frameWidth: EMOTES.icons.frameWidth,
      frameHeight: EMOTES.icons.frameHeight,
    });

    // Baked appearance sheets (on the volume, not in the image — see spec §7.2).
    // The manifest lists which hashes have been built; a missing file is not an
    // error, AppearanceResolver substitutes the fallback sheet.
    this.load.json('baked-manifest', 'assets/baked/manifest.json');
  }

  create() {
    const baked = (this.cache.json.get('baked-manifest') as { hashes?: string[] } | undefined)?.hashes ?? [];
    this.registerAgentAnimations(baked);

    for (const hash of baked) {
      this.load.spritesheet(`agent-${hash}`, `assets/baked/${hash}.png`, {
        frameWidth: AVATAR_VARIANTS[0].frameWidth,
        frameHeight: AVATAR_VARIANTS[0].frameHeight,
      });
    }
    this.load.once(Phaser.Loader.Events.COMPLETE, () => this.scene.start('DistrictScene'));
    this.load.start();
  }

  /**
   * All agent and emote animations — driven by manifest data, no magic
   * numbers. `bakedHashes` are the baked-appearance textures the manifest
   * lists (see preload()'s `baked-manifest` load) — each gets the identical
   * idle/walk/sit/sleep set registered against ITS OWN texture key, via
   * `resolvedAnimDef` (Task 30 review Finding 1 fix): without this, a
   * baked/derived sprite's animations play back against the wrong sheet the
   * instant any animation starts, because Phaser's `sprite.play()` switches
   * the sprite to whatever texture the played frames reference.
   */
  private registerAgentAnimations(bakedHashes: string[] = []) {
    const mk = (key: string, texture: string, frames: number[], frameRate: number, repeat = -1) => {
      if (this.anims.exists(key)) return;
      this.anims.create({
        key,
        frames: frames.map(f => ({ key: texture, frame: f })),
        frameRate,
        repeat,
      });
    };
    const range = (start: number, len: number) => Array.from({ length: len }, (_, i) => start + i);

    for (const v of AVATAR_VARIANTS) {
      for (const dir of DIRECTION_ORDER) {
        mk(animKey(v, 'idle', dir), v.textureKey, range(animStartFrame(v, 'idle', dir), v.framesPerDirection), ANIM_RATE.idle);
        mk(animKey(v, 'walk', dir), v.textureKey, range(animStartFrame(v, 'walk', dir), v.framesPerDirection), ANIM_RATE.walk);
      }
      if (v.rows.sit !== undefined) {
        mk(animKey(v, 'sit-right'), v.textureKey, sitFrames(v, 'right'), ANIM_RATE.sit);
        mk(animKey(v, 'sit-left'), v.textureKey, sitFrames(v, 'left'), ANIM_RATE.sit);
      }
      if (v.rows.sleep !== undefined) {
        mk(animKey(v, 'sleep'), v.textureKey, sleepFrames(v), ANIM_RATE.sleep);
      }
    }

    // Baked appearance sheets: same human layout, a fresh texture key per
    // hash. rows.sit/rows.sleep are always defined for resolvedAnimDef (it
    // clones a human), so no existence guard is needed here, unlike above.
    for (const hash of bakedHashes) {
      const v = resolvedAnimDef(`agent-${hash}`);
      for (const dir of DIRECTION_ORDER) {
        mk(animKey(v, 'idle', dir), v.textureKey, range(animStartFrame(v, 'idle', dir), v.framesPerDirection), ANIM_RATE.idle);
        mk(animKey(v, 'walk', dir), v.textureKey, range(animStartFrame(v, 'walk', dir), v.framesPerDirection), ANIM_RATE.walk);
      }
      mk(animKey(v, 'sit-right'), v.textureKey, sitFrames(v, 'right'), ANIM_RATE.sit);
      mk(animKey(v, 'sit-left'), v.textureKey, sitFrames(v, 'left'), ANIM_RATE.sit);
      mk(animKey(v, 'sleep'), v.textureKey, sleepFrames(v), ANIM_RATE.sleep);
    }

    // The "thinking" bubble: appears, then a looped "bubbling"
    mk('emote-think-appear', EMOTES.think.textureKey, [...EMOTES.think.appearFrames], EMOTES.think.frameRate, 0);
    mk('emote-think-loop', EMOTES.think.textureKey, [...EMOTES.think.loopFrames], EMOTES.think.frameRate);

    // Status icons — a two-frame pulse. The frame indices come from the pack
    // adapter via assets.generated.ts, not from code (I-1).
    for (const [statusName, pair] of Object.entries(EMOTE_FRAMES)) {
      mk(`emote-icon-${statusName}`, EMOTES.icons.textureKey, [...pair], EMOTES.icons.frameRate);
    }

    // Animated interior objects
    for (const [key, def] of Object.entries(ANIMATED_OBJECTS)) {
      mk(`anim-${key}`, `anim-${key}`, range(0, def.frames), def.frameRate);
    }
  }
}
