// GENERATED by scripts/world-bake.mjs from pack "fixture" — do not edit.
export const DISTRICT_PROPS: string[] = ["office_building","cafe_building","villa_building","library_building","barn","tree_oak_big","tree_oak_med","tree_birch","street_lamp","bench","trash_can","hydrant","car_right_1","car_left_1","car_right_2","car_down_1","car_down_2","bush_1","bush_2","crop_cabbage","crop_berry","soil_left","soil_mid","soil_right","fence_top_left","fence_top_middle","fence_top_right","fence_middle_left","fence_middle_right","fence_bottom_left","fence_bottom_middle","fence_bottom_right","tent_1","tent_2","tent_3","tent_4","tent_5","tent_6","sleeping_bag_1","sleeping_bag_2","sleeping_bag_3","sleeping_bag_4","sleeping_bag_5","campfire_1","campfire_2","campfire_3","lantern","mobile_home_small","mobile_home_medium","mobile_home_big","one_story_house","terraced_house_1","terraced_house_2","terraced_house_3","terraced_house_4","terraced_house_5","terraced_house_6","terraced_house_modular_1","terraced_house_modular_2","terraced_house_modular_3","terraced_house_modular_4","terraced_house_modular_5","terraced_house_modular_6","country_house","villa_1","villa_2","villa_3","villa_4","villa_5","villa_chimney_1","villa_chimney_2","villa_chimney_3","villa_chimney_4","villa_chimney_5","villa_roof_window_1","villa_roof_window_2","villa_roof_window_3","villa_roof_window_4","villa_roof_window_5","villa_solar_panel_1","villa_solar_panel_2","villa_solar_panel_3","villa_solar_panel_4","villa_solar_panel_5","condo_6","condo_8","condo_9","condo_7_modular_top","condo_7_modular_middle","condo_7_modular_bottom"];
export const INTERIOR_PROPS: string[] = ["bed_green","bed_blue","bed_teal","nightstand","rug_pink","chair_blue_r","chair_blue_l","chair_red_r","chair_red_l","chair_yellow_r","chair_yellow_l","table_plain","armchair_grey_r","armchair_grey_l","armchair_blue_r","armchair_blue_l","lamp_red","plant_palm","bookshelf_a","bookshelf_b","bookshelf_narrow","lectern","globe","chalkboard","counter_wide","stool","doormat","plant_small","plant_pot","office_chair_right","office_chair_left","whiteboard","printer","workstation_single","workstation_double","coffee_machine"];
export const ANIMATED_OBJECT_KEYS: string[] = ["coffee_steam","cake_fridge","tv_news","office_screen","cuckoo_clock"];
/** Frame pairs for the status icons. Pack-specific — they live in the adapter (I-1). */
export const EMOTE_FRAMES: Record<string, [number, number]> = {
  "work": [
    40,
    41
  ],
  "task_running": [
    42,
    43
  ],
  "task_done": [
    44,
    45
  ],
  "chat_npc": [
    46,
    47
  ],
  "rest": [
    48,
    49
  ],
  "error": [
    50,
    51
  ]
};
