/**
 * Config constants for the game side. No magic numbers in scenes —
 * map sizes, speeds and the camera are tuned here.
 */
import type { AgentLocation } from '@botville/shared';

export const TILE_SIZE = 16;

/** TZ-16: how often to ask the server "who is where" + the server hour, ms. */
export const LOCATION_POLL_MS = 15_000;

/**
 * TZ-16: location (server truth) -> the scene that draws it.
 * 'farm' — the farm's pen/yard, lives on the district map.
 */
export const LOCATION_SCENES: Record<AgentLocation, string> = {
  district: 'DistrictScene',
  farm: 'DistrictScene',
  office: 'OfficeScene',
  cafe: 'CafeScene',
  library: 'LibraryScene',
  dorm: 'DormScene',
} as const;

/** Leaving cosmetics (TZ-16): if the agent takes longer than this to reach the door — they vanish. */
export const LEAVE_WALK_TIMEOUT_MS = 9_000;

/** District map (generated by scripts/world-bake.mjs from venues/district/venue.json). */
export const DISTRICT = {
  mapKey: 'district',
  tilesetName: 'district_ground',
  widthTiles: 48,
  heightTiles: 46,
  get widthPx() { return this.widthTiles * TILE_SIZE; },
  get heightPx() { return this.heightTiles * TILE_SIZE; },
} as const;

export const WALK_SPEED = 48; // px/sec (16px tile, speed ~3 tiles/sec)

export const CAMERA = {
  initialZoom: 1.8,
  minZoom: 0.6,
  maxZoom: 4,
  zoomStep: 1.3,
} as const;

/** Camera drag controls (TZ-09, cameraControls.ts). */
export const CAMERA_DRAG = {
  /** Pointer movement below the threshold — click/tap, above — pan; screen px. */
  tapPx: 5,
  /** After a pinch — ignore taps so lifting a finger doesn't open an agent; ms. */
  pinchTapGuardMs: 150,
  /** Pan inertia: decay constant (sec) and start/stop threshold (px/sec). */
  inertiaTauSec: 0.25,
  inertiaMinSpeed: 60,
} as const;

/** Agent wandering: radius for picking a random point, px. */
export const WANDER_RADIUS = 120;

/** Depth of agent name labels — above props-above (tree crowns etc.). */
export const NAME_LABEL_DEPTH = 5000;

/** Game time: 1 real minute = 1 game hour. */
export const TIME = {
  msPerGameHour: 60_000,
  startHour: 10,
} as const;

/**
 * Key points of the district tint: hour -> overlay color/alpha.
 * Between points — linear lerp (wrapping around midnight): night holds
 * from 20:00 to 5:00, then dawn passes through pink to a transparent day.
 */
export const DAY_TINT_KEYS: ReadonlyArray<{ h: number; color: number; alpha: number }> = [
  { h: 5, color: 0x0a0a2e, alpha: 0.45 },    // end of night
  { h: 6.5, color: 0xff7799, alpha: 0.2 },   // dawn: pink
  { h: 8, color: 0xffbb99, alpha: 0 },       // morning: transparent
  { h: 17, color: 0xffbb99, alpha: 0 },      // day
  { h: 18.5, color: 0xff7328, alpha: 0.3 }, // sunset: orange peak
  { h: 20, color: 0x0a0a2e, alpha: 0.45 },   // night
];

/** Tint depth: above the map and agents, below glows and name labels. */
export const TINT_OVERLAY_DEPTH = 4000;

/** Night light: the glow activity window and fade smoothness (game hours). */
export const NIGHT_LIGHT = {
  start: 19,
  end: 6,
  fadeHours: 0.5,
} as const;

/** Glow sprite depth: above the tint, below name labels. */
export const GLOW_DEPTH = 4200;

/** Radial glow texture: generated once into a RenderTexture. */
export const GLOW_TEXTURE = { key: 'glow-radial', size: 64 } as const;

/** Kinds of light sources (radius in world px, alpha — maximum at night). */
export const GLOW_KINDS = {
  lamp: { color: 0xffcc88, radius: 36, alpha: 0.8 },
  window: { color: 0xffbb55, radius: 15, alpha: 0.55 },
  sign: { color: 0xffee99, radius: 22, alpha: 0.65 },
  headlight: { color: 0xffffcc, radius: 14, alpha: 0.85 },
} as const;
export type GlowKind = keyof typeof GLOW_KINDS;

/**
 * Agents' night routine (client-side cosmetics, no LLM).
 * Since TZ-16, WHERE an agent goes at night is decided by the server (world/agentLife.ts,
 * a mirror of these hours); the client keeps animals sleeping in the pen and dorm beds.
 */
export const NIGHT_SCHEDULE = {
  /** From this hour idle agents go to sleep. */
  sleepStart: 22,
  /** Wake-up window: everyone wakes at their own random hour from [wakeStart, wakeEnd). */
  wakeStart: 7,
  wakeEnd: 9,
  /** An agent woken by a click stays awake this many game hours. */
  snoozeHours: 2,
} as const;

/** Fade transition between scenes, ms. */
export const SCENE_FADE_MS = 300;

/** Camera focus on an agent when clicked in the HUD panel. */
export const CAMERA_FOCUS = { panMs: 600, zoom: 2.4 } as const;

/** Ambience: a car driving down the road every 30-45 sec. */
export const AMBIENT_CAR = {
  minIntervalSec: 30,
  maxIntervalSec: 45,
  /** The first car comes earlier so the scene feels alive right away. */
  firstDelaySec: 8,
  speed: 90, // px/sec
  /** Top of the car sprite: eastbound lane / southbound column. */
  rightLaneY: 344,
  downLaneX: 344,
} as const;

/** Interiors: scene -> map key (tilemaps are generated by scripts/world-bake.mjs). */
export const INTERIORS = {
  OfficeScene: 'office',
  CafeScene: 'cafe',
  DormScene: 'dorm',
  LibraryScene: 'library',
} as const;

export const INTERIOR_TILESET = 'interiors_ground';

/** Interior camera: a 20x15 tile room. */
export const INTERIOR_CAMERA_ZOOM = 2.4;

/** Furniture image keys: name = file assets/sprites/limezu/interior/<name>.png */
export const INTERIOR_IMAGES = [
  'bed_green', 'bed_blue', 'bed_teal', 'nightstand', 'rug_pink',
  'chair_blue_r', 'chair_blue_l', 'chair_red_r', 'chair_red_l',
  'chair_yellow_r', 'chair_yellow_l', 'table_plain',
  'armchair_grey_r', 'armchair_grey_l', 'armchair_blue_r', 'armchair_blue_l',
  'lamp_red', 'plant_palm',
  'bookshelf_a', 'bookshelf_b', 'bookshelf_narrow', 'lectern', 'globe', 'chalkboard',
  'counter_wide', 'stool', 'doormat',
  'plant_small', 'plant_pot', 'office_chair_right', 'office_chair_left',
  'whiteboard', 'printer', 'workstation_single', 'workstation_double', 'coffee_machine',
] as const;

/** District image keys: name = file assets/sprites/limezu/district/<name>.png */
export const DISTRICT_IMAGES = [
  'office_building', 'cafe_building', 'villa_building', 'library_building', 'barn',
  'tree_oak_big', 'tree_oak_med', 'tree_birch',
  'street_lamp', 'bench', 'trash_can', 'hydrant',
  'car_right_1', 'car_left_1', 'car_right_2', 'car_down_1', 'car_down_2',
  'bush_1', 'bush_2',
  'crop_cabbage', 'crop_berry', 'soil_left', 'soil_mid', 'soil_right',
  'fence_top_left', 'fence_top_middle', 'fence_top_right',
  'fence_middle_left', 'fence_middle_right',
  'fence_bottom_left', 'fence_bottom_middle', 'fence_bottom_right',
] as const;
