// GENERATED by scripts/world-bake.mjs — do not edit.
import type { VenueDescriptor } from '@botville/shared';

export const VENUES: VenueDescriptor[] = [
  {
    "id": "cafe",
    "label": "Café",
    "indoor": true,
    "sizeTiles": [
      20,
      15
    ],
    "groundAtlas": "interiors_ground",
    "capacity": 9,
    "roles": [
      "hangout",
      "work"
    ],
    "affords": [
      "eat",
      "socialize",
      "read"
    ],
    "hours": [
      {
        "open": 7,
        "close": 24
      },
      {
        "open": 0,
        "close": 2
      }
    ],
    "ground": {
      "wallA": "wallCafeA",
      "wallB": "wallCafeB",
      "floor": "floorCafe"
    },
    "furniture": [
      {
        "name": "counter_wide",
        "at": [
          2,
          3.6
        ]
      },
      {
        "name": "counter_wide",
        "at": [
          5.25,
          3.6
        ]
      },
      {
        "name": "coffee_machine",
        "at": [
          2.4,
          2
        ]
      },
      {
        "name": "stool",
        "at": [
          3,
          5.6
        ],
        "collide": false
      },
      {
        "name": "stool",
        "at": [
          5,
          5.6
        ],
        "collide": false
      },
      {
        "name": "stool",
        "at": [
          7,
          5.6
        ],
        "collide": false
      },
      {
        "name": "table_plain",
        "at": [
          3,
          8.5
        ]
      },
      {
        "name": "chair_red_r",
        "at": [
          1.4,
          8.8
        ],
        "collide": false
      },
      {
        "name": "chair_red_l",
        "at": [
          6.2,
          8.8
        ],
        "collide": false
      },
      {
        "name": "table_plain",
        "at": [
          13,
          8.5
        ]
      },
      {
        "name": "chair_red_r",
        "at": [
          11.4,
          8.8
        ],
        "collide": false
      },
      {
        "name": "chair_red_l",
        "at": [
          16.2,
          8.8
        ],
        "collide": false
      },
      {
        "name": "table_plain",
        "at": [
          4.5,
          11
        ],
        "note": "lower table sits left of the doorway: the mat (x145-175) and the entry stay clear. Offset is exactly 3.5 tiles — any less and the left chair (+3.2 tiles) lands on the mat (owner note after TZ-09)"
      },
      {
        "name": "chair_yellow_r",
        "at": [
          2.9,
          11.3
        ],
        "collide": false
      },
      {
        "name": "chair_yellow_l",
        "at": [
          7.7,
          11.3
        ],
        "collide": false
      },
      {
        "name": "plant_palm",
        "at": [
          17.5,
          1.4
        ]
      },
      {
        "name": "plant_pot",
        "at": [
          1.2,
          12
        ]
      }
    ],
    "seats": [
      {
        "at": [
          3.5,
          6.6
        ],
        "side": "right",
        "kind": "stool"
      },
      {
        "at": [
          5.5,
          6.6
        ],
        "side": "left",
        "kind": "stool"
      },
      {
        "at": [
          7.5,
          6.6
        ],
        "side": "right",
        "kind": "stool"
      },
      {
        "at": [
          2.2,
          10.6
        ],
        "side": "right",
        "kind": "chair"
      },
      {
        "at": [
          7,
          10.6
        ],
        "side": "left",
        "kind": "chair"
      },
      {
        "at": [
          12.2,
          10.6
        ],
        "side": "right",
        "kind": "chair"
      },
      {
        "at": [
          17,
          10.6
        ],
        "side": "left",
        "kind": "chair"
      },
      {
        "at": [
          3.7,
          13.1
        ],
        "side": "right",
        "kind": "chair"
      },
      {
        "at": [
          8.5,
          13.1
        ],
        "side": "left",
        "kind": "chair"
      }
    ],
    "animated": [
      {
        "name": "cake_fridge",
        "at": [
          10.5,
          1.6
        ]
      },
      {
        "name": "coffee_steam",
        "at": [
          4.8,
          2.6
        ]
      }
    ],
    "spawns": [
      [
        9.8,
        12.8
      ]
    ],
    "doors": [
      {
        "name": "exit",
        "at": [
          9.5,
          14
        ],
        "targetVenue": "district"
      }
    ],
    "glows": []
  },
  {
    "id": "district",
    "label": "District",
    "indoor": false,
    "sizeTiles": [
      48,
      46
    ],
    "groundAtlas": "district_ground",
    "capacity": 96,
    "roles": [
      "hangout"
    ],
    "affords": [
      "wander",
      "socialize",
      "idle"
    ],
    "hours": [
      {
        "open": 0,
        "close": 24
      }
    ],
    "generator": {
      "name": "cityGrid",
      "seed": 20260703,
      "params": {
        "vRoad": [
          22,
          24
        ],
        "hRoad": [
          21,
          23
        ],
        "vSidewalks": [
          [
            20,
            21
          ],
          [
            25,
            26
          ]
        ],
        "hSidewalks": [
          [
            19,
            20
          ],
          [
            24,
            25
          ]
        ],
        "pen": [
          36,
          2,
          47,
          18
        ],
        "gate": [
          40,
          42
        ],
        "paths": [
          [
            8,
            41,
            9,
            42
          ],
          [
            10,
            41,
            19,
            42
          ],
          [
            32,
            36,
            33,
            37
          ],
          [
            27,
            36,
            31,
            37
          ]
        ]
      }
    },
    "furniture": [
      {
        "name": "office_building",
        "at": [
          4,
          0
        ],
        "layer": "buildings",
        "label": "Office",
        "targetVenue": "office"
      },
      {
        "name": "cafe_building",
        "at": [
          29,
          7
        ],
        "layer": "buildings",
        "label": "Café",
        "targetVenue": "cafe"
      },
      {
        "name": "villa_building",
        "at": [
          5,
          27
        ],
        "layer": "buildings",
        "label": "Dorm",
        "targetVenue": "dorm"
      },
      {
        "name": "library_building",
        "at": [
          30,
          27
        ],
        "layer": "buildings",
        "label": "Library",
        "targetVenue": "library"
      },
      {
        "name": "barn",
        "at": [
          37,
          2
        ],
        "layer": "buildings",
        "label": "Farm"
      },
      {
        "name": "tree_oak_big",
        "at": [
          0,
          1
        ],
        "layer": "props-above"
      },
      {
        "name": "tree_oak_big",
        "at": [
          17,
          12
        ],
        "layer": "props-above"
      },
      {
        "name": "tree_oak_med",
        "at": [
          1,
          13
        ],
        "layer": "props-above"
      },
      {
        "name": "tree_oak_big",
        "at": [
          28,
          0
        ],
        "layer": "props-above"
      },
      {
        "name": "tree_birch",
        "at": [
          33,
          3
        ],
        "layer": "props-above"
      },
      {
        "name": "tree_oak_med",
        "at": [
          0,
          26
        ],
        "layer": "props-above"
      },
      {
        "name": "tree_birch",
        "at": [
          16,
          27
        ],
        "layer": "props-above"
      },
      {
        "name": "tree_oak_big",
        "at": [
          15,
          33
        ],
        "layer": "props-above"
      },
      {
        "name": "tree_oak_big",
        "at": [
          40,
          27
        ],
        "layer": "props-above"
      },
      {
        "name": "tree_oak_med",
        "at": [
          44,
          31
        ],
        "layer": "props-above"
      },
      {
        "name": "tree_oak_big",
        "at": [
          39,
          36
        ],
        "layer": "props-above"
      },
      {
        "name": "tree_birch",
        "at": [
          44,
          40
        ],
        "layer": "props-above"
      },
      {
        "name": "tree_oak_med",
        "at": [
          28,
          40
        ],
        "layer": "props-above"
      },
      {
        "name": "tree_oak_big",
        "at": [
          2,
          40
        ],
        "layer": "props-above"
      },
      {
        "name": "street_lamp",
        "at": [
          6,
          18
        ],
        "layer": "props-above",
        "type": "lamp"
      },
      {
        "name": "street_lamp",
        "at": [
          15,
          18
        ],
        "layer": "props-above",
        "type": "lamp"
      },
      {
        "name": "street_lamp",
        "at": [
          30,
          18
        ],
        "layer": "props-above",
        "type": "lamp"
      },
      {
        "name": "street_lamp",
        "at": [
          40,
          18
        ],
        "layer": "props-above",
        "type": "lamp"
      },
      {
        "name": "street_lamp",
        "at": [
          6,
          26
        ],
        "layer": "props-above",
        "type": "lamp"
      },
      {
        "name": "street_lamp",
        "at": [
          15,
          26
        ],
        "layer": "props-above",
        "type": "lamp"
      },
      {
        "name": "street_lamp",
        "at": [
          33,
          26
        ],
        "layer": "props-above",
        "type": "lamp"
      },
      {
        "name": "street_lamp",
        "at": [
          44,
          26
        ],
        "layer": "props-above",
        "type": "lamp"
      },
      {
        "name": "street_lamp",
        "at": [
          19,
          5
        ],
        "layer": "props-above",
        "type": "lamp"
      },
      {
        "name": "street_lamp",
        "at": [
          19,
          32
        ],
        "layer": "props-above",
        "type": "lamp"
      },
      {
        "name": "street_lamp",
        "at": [
          27,
          12
        ],
        "layer": "props-above",
        "type": "lamp"
      },
      {
        "name": "street_lamp",
        "at": [
          27,
          38
        ],
        "layer": "props-above",
        "type": "lamp"
      },
      {
        "name": "bench",
        "at": [
          33,
          19
        ],
        "layer": "props-above"
      },
      {
        "name": "bench",
        "at": [
          12,
          24
        ],
        "layer": "props-above"
      },
      {
        "name": "bench",
        "at": [
          42,
          33
        ],
        "layer": "props-above"
      },
      {
        "name": "trash_can",
        "at": [
          36,
          19
        ],
        "layer": "props-above"
      },
      {
        "name": "trash_can",
        "at": [
          17,
          24
        ],
        "layer": "props-above"
      },
      {
        "name": "hydrant",
        "at": [
          17,
          18
        ],
        "layer": "props-above"
      },
      {
        "name": "car_right_1",
        "at": [
          8,
          22.6
        ],
        "layer": "props-above"
      },
      {
        "name": "car_left_1",
        "at": [
          33,
          19.1
        ],
        "layer": "props-above",
        "note": "red car parks against the north kerb, half the body on the pavement"
      },
      {
        "name": "car_right_1",
        "at": [
          42,
          22.6
        ],
        "layer": "props-above"
      }
    ],
    "scatter": {
      "bushes": {
        "at": [
          [
            3,
            19
          ],
          [
            10,
            19
          ],
          [
            28,
            19
          ],
          [
            38,
            19
          ],
          [
            3,
            25
          ],
          [
            16,
            26
          ],
          [
            29,
            26
          ],
          [
            35,
            26
          ],
          [
            46,
            20
          ]
        ],
        "pick": [
          "bush_1",
          "bush_2"
        ],
        "layer": "props-above"
      },
      "fence": {
        "prefix": "fence_",
        "layer": "props-above"
      },
      "crops": {
        "rows": 3,
        "startTile": [
          37,
          13
        ],
        "step": 2,
        "alternate": [
          "crop_cabbage",
          "crop_berry"
        ],
        "layer": "props-below"
      }
    },
    "seats": [],
    "spawns": [
      [
        21,
        19.75
      ],
      [
        26.875,
        19.75
      ],
      [
        21,
        25.625
      ],
      [
        26.875,
        25.625
      ],
      [
        11.25,
        19.875
      ],
      [
        35,
        25.625
      ],
      [
        21,
        12.5
      ],
      [
        26.25,
        32.5
      ]
    ],
    "animated": [],
    "doors": [
      {
        "name": "office_door",
        "at": [
          9,
          18
        ],
        "targetVenue": "office",
        "sizePx": [
          48,
          16
        ]
      },
      {
        "name": "cafe_door",
        "at": [
          31,
          18
        ],
        "targetVenue": "cafe",
        "sizePx": [
          48,
          16
        ]
      },
      {
        "name": "villa_door",
        "at": [
          7.5,
          40
        ],
        "targetVenue": "dorm",
        "sizePx": [
          48,
          16
        ]
      },
      {
        "name": "library_door",
        "at": [
          32,
          35
        ],
        "targetVenue": "library",
        "sizePx": [
          48,
          16
        ]
      }
    ],
    "glows": [
      {
        "kind": "lamp",
        "at": [
          117,
          302
        ]
      },
      {
        "kind": "lamp",
        "at": [
          261,
          302
        ]
      },
      {
        "kind": "lamp",
        "at": [
          501,
          302
        ]
      },
      {
        "kind": "lamp",
        "at": [
          661,
          302
        ]
      },
      {
        "kind": "lamp",
        "at": [
          117,
          430
        ]
      },
      {
        "kind": "lamp",
        "at": [
          261,
          430
        ]
      },
      {
        "kind": "lamp",
        "at": [
          549,
          430
        ]
      },
      {
        "kind": "lamp",
        "at": [
          725,
          430
        ]
      },
      {
        "kind": "lamp",
        "at": [
          325,
          94
        ]
      },
      {
        "kind": "lamp",
        "at": [
          325,
          526
        ]
      },
      {
        "kind": "lamp",
        "at": [
          453,
          206
        ]
      },
      {
        "kind": "lamp",
        "at": [
          453,
          622
        ]
      },
      {
        "kind": "sign",
        "at": [
          189,
          146
        ]
      },
      {
        "kind": "window",
        "at": [
          94,
          170
        ]
      },
      {
        "kind": "window",
        "at": [
          154,
          170
        ]
      },
      {
        "kind": "window",
        "at": [
          94,
          202
        ]
      },
      {
        "kind": "window",
        "at": [
          154,
          202
        ]
      },
      {
        "kind": "window",
        "at": [
          94,
          234
        ]
      },
      {
        "kind": "window",
        "at": [
          154,
          234
        ]
      },
      {
        "kind": "window",
        "at": [
          94,
          266
        ]
      },
      {
        "kind": "window",
        "at": [
          154,
          266
        ]
      },
      {
        "kind": "window",
        "at": [
          214,
          180
        ]
      },
      {
        "kind": "window",
        "at": [
          214,
          240
        ]
      },
      {
        "kind": "sign",
        "at": [
          520,
          242
        ]
      },
      {
        "kind": "window",
        "at": [
          489,
          270
        ]
      },
      {
        "kind": "window",
        "at": [
          551,
          270
        ]
      },
      {
        "kind": "window",
        "at": [
          116,
          540
        ]
      },
      {
        "kind": "window",
        "at": [
          180,
          540
        ]
      },
      {
        "kind": "window",
        "at": [
          126,
          598
        ]
      },
      {
        "kind": "window",
        "at": [
          192,
          598
        ]
      },
      {
        "kind": "sign",
        "at": [
          544,
          523
        ]
      },
      {
        "kind": "window",
        "at": [
          500,
          560
        ]
      },
      {
        "kind": "window",
        "at": [
          544,
          560
        ]
      },
      {
        "kind": "window",
        "at": [
          588,
          560
        ]
      }
    ],
    "night": [
      {
        "name": "animal_sleep",
        "atPx": [
          656,
          220
        ]
      },
      {
        "name": "animal_sleep",
        "atPx": [
          700,
          232
        ]
      },
      {
        "name": "animal_sleep",
        "atPx": [
          672,
          258
        ]
      },
      {
        "name": "animal_sleep",
        "atPx": [
          726,
          262
        ]
      }
    ]
  },
  {
    "id": "dorm",
    "label": "Dorm",
    "indoor": true,
    "sizeTiles": [
      20,
      15
    ],
    "groundAtlas": "interiors_ground",
    "capacity": 6,
    "roles": [
      "hangout"
    ],
    "affords": [
      "socialize",
      "idle"
    ],
    "hours": [
      {
        "open": 0,
        "close": 24
      }
    ],
    "ground": {
      "wallA": "wallDormA",
      "wallB": "wallDormB",
      "floor": "floorDorm"
    },
    "furniture": [
      {
        "name": "bed_green",
        "at": [
          2,
          1.6
        ]
      },
      {
        "name": "bed_blue",
        "at": [
          6,
          1.6
        ]
      },
      {
        "name": "bed_teal",
        "at": [
          12,
          1.6
        ]
      },
      {
        "name": "bed_green",
        "at": [
          16,
          1.6
        ]
      },
      {
        "name": "nightstand",
        "at": [
          4.3,
          2.4
        ]
      },
      {
        "name": "nightstand",
        "at": [
          14.3,
          2.4
        ]
      },
      {
        "name": "rug_pink",
        "at": [
          8,
          8.4
        ],
        "collide": false
      },
      {
        "name": "armchair_grey_r",
        "at": [
          6,
          7.25
        ],
        "note": "armchair bottom (42px from ty) sits on the seat line — a seated agent draws over the seat, the back rises above their head"
      },
      {
        "name": "armchair_grey_l",
        "at": [
          12.2,
          7.25
        ]
      },
      {
        "name": "plant_palm",
        "at": [
          1.2,
          8
        ]
      },
      {
        "name": "lamp_red",
        "at": [
          18,
          7.6
        ]
      },
      {
        "name": "plant_pot",
        "at": [
          18,
          12
        ]
      }
    ],
    "seats": [
      {
        "at": [
          2.8,
          3.4
        ],
        "side": "right",
        "kind": "bed"
      },
      {
        "at": [
          6.8,
          3.4
        ],
        "side": "right",
        "kind": "bed"
      },
      {
        "at": [
          12.8,
          3.4
        ],
        "side": "left",
        "kind": "bed"
      },
      {
        "at": [
          16.8,
          3.4
        ],
        "side": "left",
        "kind": "bed"
      },
      {
        "at": [
          6.9,
          9.9
        ],
        "side": "right",
        "kind": "chair"
      },
      {
        "at": [
          13,
          9.9
        ],
        "side": "left",
        "kind": "chair"
      }
    ],
    "animated": [
      {
        "name": "tv_news",
        "at": [
          9,
          0.4
        ]
      }
    ],
    "spawns": [
      [
        9.8,
        12.8
      ]
    ],
    "doors": [
      {
        "name": "exit",
        "at": [
          9.5,
          14
        ],
        "targetVenue": "district"
      }
    ],
    "glows": []
  },
  {
    "archetype": "house",
    "indoor": true,
    "sizeTiles": [
      20,
      15
    ],
    "groundAtlas": "interiors_ground",
    "capacity": 7,
    "roles": [
      "home"
    ],
    "affords": [
      "sleep",
      "idle"
    ],
    "hours": [
      {
        "open": 0,
        "close": 24
      }
    ],
    "ground": {
      "wallA": "wallDormA",
      "wallB": "wallDormB",
      "floor": "floorDorm"
    },
    "furniture": [
      {
        "name": "bed_green",
        "at": [
          2,
          1.6
        ]
      },
      {
        "name": "bed_blue",
        "at": [
          6,
          1.6
        ]
      },
      {
        "name": "bed_teal",
        "at": [
          12,
          1.6
        ]
      },
      {
        "name": "bed_green",
        "at": [
          16,
          1.6
        ]
      },
      {
        "name": "nightstand",
        "at": [
          4.3,
          2.4
        ]
      },
      {
        "name": "nightstand",
        "at": [
          14.3,
          2.4
        ]
      },
      {
        "name": "table_plain",
        "at": [
          8.5,
          7.5
        ]
      },
      {
        "name": "chair_red_r",
        "at": [
          6.9,
          7.8
        ],
        "collide": false
      },
      {
        "name": "chair_red_l",
        "at": [
          11.7,
          7.8
        ],
        "collide": false
      },
      {
        "name": "armchair_grey_r",
        "at": [
          2.6,
          10.6
        ]
      },
      {
        "name": "rug_pink",
        "at": [
          8,
          10.4
        ],
        "collide": false
      },
      {
        "name": "lamp_red",
        "at": [
          18,
          7.6
        ]
      },
      {
        "name": "plant_pot",
        "at": [
          1.2,
          12
        ]
      }
    ],
    "seats": [
      {
        "at": [
          2.8,
          3.4
        ],
        "side": "right",
        "kind": "bed"
      },
      {
        "at": [
          6.8,
          3.4
        ],
        "side": "right",
        "kind": "bed"
      },
      {
        "at": [
          12.8,
          3.4
        ],
        "side": "left",
        "kind": "bed"
      },
      {
        "at": [
          16.8,
          3.4
        ],
        "side": "left",
        "kind": "bed"
      },
      {
        "at": [
          7.7,
          9.6
        ],
        "side": "right",
        "kind": "chair"
      },
      {
        "at": [
          12.5,
          9.6
        ],
        "side": "left",
        "kind": "chair"
      },
      {
        "at": [
          3.5,
          13.2
        ],
        "side": "right",
        "kind": "chair"
      }
    ],
    "animated": [
      {
        "name": "tv_news",
        "at": [
          9,
          0.4
        ]
      }
    ],
    "spawns": [
      [
        9.8,
        12.8
      ]
    ],
    "doors": [
      {
        "name": "exit",
        "at": [
          9.5,
          14
        ],
        "targetVenue": "district"
      }
    ],
    "glows": [],
    "id": "house_1",
    "label": "House 1"
  },
  {
    "archetype": "house",
    "indoor": true,
    "sizeTiles": [
      20,
      15
    ],
    "groundAtlas": "interiors_ground",
    "capacity": 7,
    "roles": [
      "home"
    ],
    "affords": [
      "sleep",
      "idle"
    ],
    "hours": [
      {
        "open": 0,
        "close": 24
      }
    ],
    "ground": {
      "wallA": "wallDormA",
      "wallB": "wallDormB",
      "floor": "floorDorm"
    },
    "furniture": [
      {
        "name": "bed_green",
        "at": [
          2,
          1.6
        ]
      },
      {
        "name": "bed_blue",
        "at": [
          6,
          1.6
        ]
      },
      {
        "name": "bed_teal",
        "at": [
          12,
          1.6
        ]
      },
      {
        "name": "bed_green",
        "at": [
          16,
          1.6
        ]
      },
      {
        "name": "nightstand",
        "at": [
          4.3,
          2.4
        ]
      },
      {
        "name": "nightstand",
        "at": [
          14.3,
          2.4
        ]
      },
      {
        "name": "table_plain",
        "at": [
          8.5,
          7.5
        ]
      },
      {
        "name": "chair_red_r",
        "at": [
          6.9,
          7.8
        ],
        "collide": false
      },
      {
        "name": "chair_red_l",
        "at": [
          11.7,
          7.8
        ],
        "collide": false
      },
      {
        "name": "armchair_grey_r",
        "at": [
          2.6,
          10.6
        ]
      },
      {
        "name": "rug_pink",
        "at": [
          8,
          10.4
        ],
        "collide": false
      },
      {
        "name": "lamp_red",
        "at": [
          18,
          7.6
        ]
      },
      {
        "name": "plant_pot",
        "at": [
          1.2,
          12
        ]
      }
    ],
    "seats": [
      {
        "at": [
          2.8,
          3.4
        ],
        "side": "right",
        "kind": "bed"
      },
      {
        "at": [
          6.8,
          3.4
        ],
        "side": "right",
        "kind": "bed"
      },
      {
        "at": [
          12.8,
          3.4
        ],
        "side": "left",
        "kind": "bed"
      },
      {
        "at": [
          16.8,
          3.4
        ],
        "side": "left",
        "kind": "bed"
      },
      {
        "at": [
          7.7,
          9.6
        ],
        "side": "right",
        "kind": "chair"
      },
      {
        "at": [
          12.5,
          9.6
        ],
        "side": "left",
        "kind": "chair"
      },
      {
        "at": [
          3.5,
          13.2
        ],
        "side": "right",
        "kind": "chair"
      }
    ],
    "animated": [
      {
        "name": "tv_news",
        "at": [
          9,
          0.4
        ]
      }
    ],
    "spawns": [
      [
        9.8,
        12.8
      ]
    ],
    "doors": [
      {
        "name": "exit",
        "at": [
          9.5,
          14
        ],
        "targetVenue": "district"
      }
    ],
    "glows": [],
    "id": "house_10",
    "label": "House 10"
  },
  {
    "archetype": "house",
    "indoor": true,
    "sizeTiles": [
      20,
      15
    ],
    "groundAtlas": "interiors_ground",
    "capacity": 7,
    "roles": [
      "home"
    ],
    "affords": [
      "sleep",
      "idle"
    ],
    "hours": [
      {
        "open": 0,
        "close": 24
      }
    ],
    "ground": {
      "wallA": "wallDormA",
      "wallB": "wallDormB",
      "floor": "floorDorm"
    },
    "furniture": [
      {
        "name": "bed_green",
        "at": [
          2,
          1.6
        ]
      },
      {
        "name": "bed_blue",
        "at": [
          6,
          1.6
        ]
      },
      {
        "name": "bed_teal",
        "at": [
          12,
          1.6
        ]
      },
      {
        "name": "bed_green",
        "at": [
          16,
          1.6
        ]
      },
      {
        "name": "nightstand",
        "at": [
          4.3,
          2.4
        ]
      },
      {
        "name": "nightstand",
        "at": [
          14.3,
          2.4
        ]
      },
      {
        "name": "table_plain",
        "at": [
          8.5,
          7.5
        ]
      },
      {
        "name": "chair_red_r",
        "at": [
          6.9,
          7.8
        ],
        "collide": false
      },
      {
        "name": "chair_red_l",
        "at": [
          11.7,
          7.8
        ],
        "collide": false
      },
      {
        "name": "armchair_grey_r",
        "at": [
          2.6,
          10.6
        ]
      },
      {
        "name": "rug_pink",
        "at": [
          8,
          10.4
        ],
        "collide": false
      },
      {
        "name": "lamp_red",
        "at": [
          18,
          7.6
        ]
      },
      {
        "name": "plant_pot",
        "at": [
          1.2,
          12
        ]
      }
    ],
    "seats": [
      {
        "at": [
          2.8,
          3.4
        ],
        "side": "right",
        "kind": "bed"
      },
      {
        "at": [
          6.8,
          3.4
        ],
        "side": "right",
        "kind": "bed"
      },
      {
        "at": [
          12.8,
          3.4
        ],
        "side": "left",
        "kind": "bed"
      },
      {
        "at": [
          16.8,
          3.4
        ],
        "side": "left",
        "kind": "bed"
      },
      {
        "at": [
          7.7,
          9.6
        ],
        "side": "right",
        "kind": "chair"
      },
      {
        "at": [
          12.5,
          9.6
        ],
        "side": "left",
        "kind": "chair"
      },
      {
        "at": [
          3.5,
          13.2
        ],
        "side": "right",
        "kind": "chair"
      }
    ],
    "animated": [
      {
        "name": "tv_news",
        "at": [
          9,
          0.4
        ]
      }
    ],
    "spawns": [
      [
        9.8,
        12.8
      ]
    ],
    "doors": [
      {
        "name": "exit",
        "at": [
          9.5,
          14
        ],
        "targetVenue": "district"
      }
    ],
    "glows": [],
    "id": "house_11",
    "label": "House 11"
  },
  {
    "archetype": "house",
    "indoor": true,
    "sizeTiles": [
      20,
      15
    ],
    "groundAtlas": "interiors_ground",
    "capacity": 7,
    "roles": [
      "home"
    ],
    "affords": [
      "sleep",
      "idle"
    ],
    "hours": [
      {
        "open": 0,
        "close": 24
      }
    ],
    "ground": {
      "wallA": "wallDormA",
      "wallB": "wallDormB",
      "floor": "floorDorm"
    },
    "furniture": [
      {
        "name": "bed_green",
        "at": [
          2,
          1.6
        ]
      },
      {
        "name": "bed_blue",
        "at": [
          6,
          1.6
        ]
      },
      {
        "name": "bed_teal",
        "at": [
          12,
          1.6
        ]
      },
      {
        "name": "bed_green",
        "at": [
          16,
          1.6
        ]
      },
      {
        "name": "nightstand",
        "at": [
          4.3,
          2.4
        ]
      },
      {
        "name": "nightstand",
        "at": [
          14.3,
          2.4
        ]
      },
      {
        "name": "table_plain",
        "at": [
          8.5,
          7.5
        ]
      },
      {
        "name": "chair_red_r",
        "at": [
          6.9,
          7.8
        ],
        "collide": false
      },
      {
        "name": "chair_red_l",
        "at": [
          11.7,
          7.8
        ],
        "collide": false
      },
      {
        "name": "armchair_grey_r",
        "at": [
          2.6,
          10.6
        ]
      },
      {
        "name": "rug_pink",
        "at": [
          8,
          10.4
        ],
        "collide": false
      },
      {
        "name": "lamp_red",
        "at": [
          18,
          7.6
        ]
      },
      {
        "name": "plant_pot",
        "at": [
          1.2,
          12
        ]
      }
    ],
    "seats": [
      {
        "at": [
          2.8,
          3.4
        ],
        "side": "right",
        "kind": "bed"
      },
      {
        "at": [
          6.8,
          3.4
        ],
        "side": "right",
        "kind": "bed"
      },
      {
        "at": [
          12.8,
          3.4
        ],
        "side": "left",
        "kind": "bed"
      },
      {
        "at": [
          16.8,
          3.4
        ],
        "side": "left",
        "kind": "bed"
      },
      {
        "at": [
          7.7,
          9.6
        ],
        "side": "right",
        "kind": "chair"
      },
      {
        "at": [
          12.5,
          9.6
        ],
        "side": "left",
        "kind": "chair"
      },
      {
        "at": [
          3.5,
          13.2
        ],
        "side": "right",
        "kind": "chair"
      }
    ],
    "animated": [
      {
        "name": "tv_news",
        "at": [
          9,
          0.4
        ]
      }
    ],
    "spawns": [
      [
        9.8,
        12.8
      ]
    ],
    "doors": [
      {
        "name": "exit",
        "at": [
          9.5,
          14
        ],
        "targetVenue": "district"
      }
    ],
    "glows": [],
    "id": "house_12",
    "label": "House 12"
  },
  {
    "archetype": "house",
    "indoor": true,
    "sizeTiles": [
      20,
      15
    ],
    "groundAtlas": "interiors_ground",
    "capacity": 7,
    "roles": [
      "home"
    ],
    "affords": [
      "sleep",
      "idle"
    ],
    "hours": [
      {
        "open": 0,
        "close": 24
      }
    ],
    "ground": {
      "wallA": "wallDormA",
      "wallB": "wallDormB",
      "floor": "floorDorm"
    },
    "furniture": [
      {
        "name": "bed_green",
        "at": [
          2,
          1.6
        ]
      },
      {
        "name": "bed_blue",
        "at": [
          6,
          1.6
        ]
      },
      {
        "name": "bed_teal",
        "at": [
          12,
          1.6
        ]
      },
      {
        "name": "bed_green",
        "at": [
          16,
          1.6
        ]
      },
      {
        "name": "nightstand",
        "at": [
          4.3,
          2.4
        ]
      },
      {
        "name": "nightstand",
        "at": [
          14.3,
          2.4
        ]
      },
      {
        "name": "table_plain",
        "at": [
          8.5,
          7.5
        ]
      },
      {
        "name": "chair_red_r",
        "at": [
          6.9,
          7.8
        ],
        "collide": false
      },
      {
        "name": "chair_red_l",
        "at": [
          11.7,
          7.8
        ],
        "collide": false
      },
      {
        "name": "armchair_grey_r",
        "at": [
          2.6,
          10.6
        ]
      },
      {
        "name": "rug_pink",
        "at": [
          8,
          10.4
        ],
        "collide": false
      },
      {
        "name": "lamp_red",
        "at": [
          18,
          7.6
        ]
      },
      {
        "name": "plant_pot",
        "at": [
          1.2,
          12
        ]
      }
    ],
    "seats": [
      {
        "at": [
          2.8,
          3.4
        ],
        "side": "right",
        "kind": "bed"
      },
      {
        "at": [
          6.8,
          3.4
        ],
        "side": "right",
        "kind": "bed"
      },
      {
        "at": [
          12.8,
          3.4
        ],
        "side": "left",
        "kind": "bed"
      },
      {
        "at": [
          16.8,
          3.4
        ],
        "side": "left",
        "kind": "bed"
      },
      {
        "at": [
          7.7,
          9.6
        ],
        "side": "right",
        "kind": "chair"
      },
      {
        "at": [
          12.5,
          9.6
        ],
        "side": "left",
        "kind": "chair"
      },
      {
        "at": [
          3.5,
          13.2
        ],
        "side": "right",
        "kind": "chair"
      }
    ],
    "animated": [
      {
        "name": "tv_news",
        "at": [
          9,
          0.4
        ]
      }
    ],
    "spawns": [
      [
        9.8,
        12.8
      ]
    ],
    "doors": [
      {
        "name": "exit",
        "at": [
          9.5,
          14
        ],
        "targetVenue": "district"
      }
    ],
    "glows": [],
    "id": "house_13",
    "label": "House 13"
  },
  {
    "archetype": "house",
    "indoor": true,
    "sizeTiles": [
      20,
      15
    ],
    "groundAtlas": "interiors_ground",
    "capacity": 7,
    "roles": [
      "home"
    ],
    "affords": [
      "sleep",
      "idle"
    ],
    "hours": [
      {
        "open": 0,
        "close": 24
      }
    ],
    "ground": {
      "wallA": "wallDormA",
      "wallB": "wallDormB",
      "floor": "floorDorm"
    },
    "furniture": [
      {
        "name": "bed_green",
        "at": [
          2,
          1.6
        ]
      },
      {
        "name": "bed_blue",
        "at": [
          6,
          1.6
        ]
      },
      {
        "name": "bed_teal",
        "at": [
          12,
          1.6
        ]
      },
      {
        "name": "bed_green",
        "at": [
          16,
          1.6
        ]
      },
      {
        "name": "nightstand",
        "at": [
          4.3,
          2.4
        ]
      },
      {
        "name": "nightstand",
        "at": [
          14.3,
          2.4
        ]
      },
      {
        "name": "table_plain",
        "at": [
          8.5,
          7.5
        ]
      },
      {
        "name": "chair_red_r",
        "at": [
          6.9,
          7.8
        ],
        "collide": false
      },
      {
        "name": "chair_red_l",
        "at": [
          11.7,
          7.8
        ],
        "collide": false
      },
      {
        "name": "armchair_grey_r",
        "at": [
          2.6,
          10.6
        ]
      },
      {
        "name": "rug_pink",
        "at": [
          8,
          10.4
        ],
        "collide": false
      },
      {
        "name": "lamp_red",
        "at": [
          18,
          7.6
        ]
      },
      {
        "name": "plant_pot",
        "at": [
          1.2,
          12
        ]
      }
    ],
    "seats": [
      {
        "at": [
          2.8,
          3.4
        ],
        "side": "right",
        "kind": "bed"
      },
      {
        "at": [
          6.8,
          3.4
        ],
        "side": "right",
        "kind": "bed"
      },
      {
        "at": [
          12.8,
          3.4
        ],
        "side": "left",
        "kind": "bed"
      },
      {
        "at": [
          16.8,
          3.4
        ],
        "side": "left",
        "kind": "bed"
      },
      {
        "at": [
          7.7,
          9.6
        ],
        "side": "right",
        "kind": "chair"
      },
      {
        "at": [
          12.5,
          9.6
        ],
        "side": "left",
        "kind": "chair"
      },
      {
        "at": [
          3.5,
          13.2
        ],
        "side": "right",
        "kind": "chair"
      }
    ],
    "animated": [
      {
        "name": "tv_news",
        "at": [
          9,
          0.4
        ]
      }
    ],
    "spawns": [
      [
        9.8,
        12.8
      ]
    ],
    "doors": [
      {
        "name": "exit",
        "at": [
          9.5,
          14
        ],
        "targetVenue": "district"
      }
    ],
    "glows": [],
    "id": "house_2",
    "label": "House 2"
  },
  {
    "archetype": "house",
    "indoor": true,
    "sizeTiles": [
      20,
      15
    ],
    "groundAtlas": "interiors_ground",
    "capacity": 7,
    "roles": [
      "home"
    ],
    "affords": [
      "sleep",
      "idle"
    ],
    "hours": [
      {
        "open": 0,
        "close": 24
      }
    ],
    "ground": {
      "wallA": "wallDormA",
      "wallB": "wallDormB",
      "floor": "floorDorm"
    },
    "furniture": [
      {
        "name": "bed_green",
        "at": [
          2,
          1.6
        ]
      },
      {
        "name": "bed_blue",
        "at": [
          6,
          1.6
        ]
      },
      {
        "name": "bed_teal",
        "at": [
          12,
          1.6
        ]
      },
      {
        "name": "bed_green",
        "at": [
          16,
          1.6
        ]
      },
      {
        "name": "nightstand",
        "at": [
          4.3,
          2.4
        ]
      },
      {
        "name": "nightstand",
        "at": [
          14.3,
          2.4
        ]
      },
      {
        "name": "table_plain",
        "at": [
          8.5,
          7.5
        ]
      },
      {
        "name": "chair_red_r",
        "at": [
          6.9,
          7.8
        ],
        "collide": false
      },
      {
        "name": "chair_red_l",
        "at": [
          11.7,
          7.8
        ],
        "collide": false
      },
      {
        "name": "armchair_grey_r",
        "at": [
          2.6,
          10.6
        ]
      },
      {
        "name": "rug_pink",
        "at": [
          8,
          10.4
        ],
        "collide": false
      },
      {
        "name": "lamp_red",
        "at": [
          18,
          7.6
        ]
      },
      {
        "name": "plant_pot",
        "at": [
          1.2,
          12
        ]
      }
    ],
    "seats": [
      {
        "at": [
          2.8,
          3.4
        ],
        "side": "right",
        "kind": "bed"
      },
      {
        "at": [
          6.8,
          3.4
        ],
        "side": "right",
        "kind": "bed"
      },
      {
        "at": [
          12.8,
          3.4
        ],
        "side": "left",
        "kind": "bed"
      },
      {
        "at": [
          16.8,
          3.4
        ],
        "side": "left",
        "kind": "bed"
      },
      {
        "at": [
          7.7,
          9.6
        ],
        "side": "right",
        "kind": "chair"
      },
      {
        "at": [
          12.5,
          9.6
        ],
        "side": "left",
        "kind": "chair"
      },
      {
        "at": [
          3.5,
          13.2
        ],
        "side": "right",
        "kind": "chair"
      }
    ],
    "animated": [
      {
        "name": "tv_news",
        "at": [
          9,
          0.4
        ]
      }
    ],
    "spawns": [
      [
        9.8,
        12.8
      ]
    ],
    "doors": [
      {
        "name": "exit",
        "at": [
          9.5,
          14
        ],
        "targetVenue": "district"
      }
    ],
    "glows": [],
    "id": "house_3",
    "label": "House 3"
  },
  {
    "archetype": "house",
    "indoor": true,
    "sizeTiles": [
      20,
      15
    ],
    "groundAtlas": "interiors_ground",
    "capacity": 7,
    "roles": [
      "home"
    ],
    "affords": [
      "sleep",
      "idle"
    ],
    "hours": [
      {
        "open": 0,
        "close": 24
      }
    ],
    "ground": {
      "wallA": "wallDormA",
      "wallB": "wallDormB",
      "floor": "floorDorm"
    },
    "furniture": [
      {
        "name": "bed_green",
        "at": [
          2,
          1.6
        ]
      },
      {
        "name": "bed_blue",
        "at": [
          6,
          1.6
        ]
      },
      {
        "name": "bed_teal",
        "at": [
          12,
          1.6
        ]
      },
      {
        "name": "bed_green",
        "at": [
          16,
          1.6
        ]
      },
      {
        "name": "nightstand",
        "at": [
          4.3,
          2.4
        ]
      },
      {
        "name": "nightstand",
        "at": [
          14.3,
          2.4
        ]
      },
      {
        "name": "table_plain",
        "at": [
          8.5,
          7.5
        ]
      },
      {
        "name": "chair_red_r",
        "at": [
          6.9,
          7.8
        ],
        "collide": false
      },
      {
        "name": "chair_red_l",
        "at": [
          11.7,
          7.8
        ],
        "collide": false
      },
      {
        "name": "armchair_grey_r",
        "at": [
          2.6,
          10.6
        ]
      },
      {
        "name": "rug_pink",
        "at": [
          8,
          10.4
        ],
        "collide": false
      },
      {
        "name": "lamp_red",
        "at": [
          18,
          7.6
        ]
      },
      {
        "name": "plant_pot",
        "at": [
          1.2,
          12
        ]
      }
    ],
    "seats": [
      {
        "at": [
          2.8,
          3.4
        ],
        "side": "right",
        "kind": "bed"
      },
      {
        "at": [
          6.8,
          3.4
        ],
        "side": "right",
        "kind": "bed"
      },
      {
        "at": [
          12.8,
          3.4
        ],
        "side": "left",
        "kind": "bed"
      },
      {
        "at": [
          16.8,
          3.4
        ],
        "side": "left",
        "kind": "bed"
      },
      {
        "at": [
          7.7,
          9.6
        ],
        "side": "right",
        "kind": "chair"
      },
      {
        "at": [
          12.5,
          9.6
        ],
        "side": "left",
        "kind": "chair"
      },
      {
        "at": [
          3.5,
          13.2
        ],
        "side": "right",
        "kind": "chair"
      }
    ],
    "animated": [
      {
        "name": "tv_news",
        "at": [
          9,
          0.4
        ]
      }
    ],
    "spawns": [
      [
        9.8,
        12.8
      ]
    ],
    "doors": [
      {
        "name": "exit",
        "at": [
          9.5,
          14
        ],
        "targetVenue": "district"
      }
    ],
    "glows": [],
    "id": "house_4",
    "label": "House 4"
  },
  {
    "archetype": "house",
    "indoor": true,
    "sizeTiles": [
      20,
      15
    ],
    "groundAtlas": "interiors_ground",
    "capacity": 7,
    "roles": [
      "home"
    ],
    "affords": [
      "sleep",
      "idle"
    ],
    "hours": [
      {
        "open": 0,
        "close": 24
      }
    ],
    "ground": {
      "wallA": "wallDormA",
      "wallB": "wallDormB",
      "floor": "floorDorm"
    },
    "furniture": [
      {
        "name": "bed_green",
        "at": [
          2,
          1.6
        ]
      },
      {
        "name": "bed_blue",
        "at": [
          6,
          1.6
        ]
      },
      {
        "name": "bed_teal",
        "at": [
          12,
          1.6
        ]
      },
      {
        "name": "bed_green",
        "at": [
          16,
          1.6
        ]
      },
      {
        "name": "nightstand",
        "at": [
          4.3,
          2.4
        ]
      },
      {
        "name": "nightstand",
        "at": [
          14.3,
          2.4
        ]
      },
      {
        "name": "table_plain",
        "at": [
          8.5,
          7.5
        ]
      },
      {
        "name": "chair_red_r",
        "at": [
          6.9,
          7.8
        ],
        "collide": false
      },
      {
        "name": "chair_red_l",
        "at": [
          11.7,
          7.8
        ],
        "collide": false
      },
      {
        "name": "armchair_grey_r",
        "at": [
          2.6,
          10.6
        ]
      },
      {
        "name": "rug_pink",
        "at": [
          8,
          10.4
        ],
        "collide": false
      },
      {
        "name": "lamp_red",
        "at": [
          18,
          7.6
        ]
      },
      {
        "name": "plant_pot",
        "at": [
          1.2,
          12
        ]
      }
    ],
    "seats": [
      {
        "at": [
          2.8,
          3.4
        ],
        "side": "right",
        "kind": "bed"
      },
      {
        "at": [
          6.8,
          3.4
        ],
        "side": "right",
        "kind": "bed"
      },
      {
        "at": [
          12.8,
          3.4
        ],
        "side": "left",
        "kind": "bed"
      },
      {
        "at": [
          16.8,
          3.4
        ],
        "side": "left",
        "kind": "bed"
      },
      {
        "at": [
          7.7,
          9.6
        ],
        "side": "right",
        "kind": "chair"
      },
      {
        "at": [
          12.5,
          9.6
        ],
        "side": "left",
        "kind": "chair"
      },
      {
        "at": [
          3.5,
          13.2
        ],
        "side": "right",
        "kind": "chair"
      }
    ],
    "animated": [
      {
        "name": "tv_news",
        "at": [
          9,
          0.4
        ]
      }
    ],
    "spawns": [
      [
        9.8,
        12.8
      ]
    ],
    "doors": [
      {
        "name": "exit",
        "at": [
          9.5,
          14
        ],
        "targetVenue": "district"
      }
    ],
    "glows": [],
    "id": "house_5",
    "label": "House 5"
  },
  {
    "archetype": "house",
    "indoor": true,
    "sizeTiles": [
      20,
      15
    ],
    "groundAtlas": "interiors_ground",
    "capacity": 7,
    "roles": [
      "home"
    ],
    "affords": [
      "sleep",
      "idle"
    ],
    "hours": [
      {
        "open": 0,
        "close": 24
      }
    ],
    "ground": {
      "wallA": "wallDormA",
      "wallB": "wallDormB",
      "floor": "floorDorm"
    },
    "furniture": [
      {
        "name": "bed_green",
        "at": [
          2,
          1.6
        ]
      },
      {
        "name": "bed_blue",
        "at": [
          6,
          1.6
        ]
      },
      {
        "name": "bed_teal",
        "at": [
          12,
          1.6
        ]
      },
      {
        "name": "bed_green",
        "at": [
          16,
          1.6
        ]
      },
      {
        "name": "nightstand",
        "at": [
          4.3,
          2.4
        ]
      },
      {
        "name": "nightstand",
        "at": [
          14.3,
          2.4
        ]
      },
      {
        "name": "table_plain",
        "at": [
          8.5,
          7.5
        ]
      },
      {
        "name": "chair_red_r",
        "at": [
          6.9,
          7.8
        ],
        "collide": false
      },
      {
        "name": "chair_red_l",
        "at": [
          11.7,
          7.8
        ],
        "collide": false
      },
      {
        "name": "armchair_grey_r",
        "at": [
          2.6,
          10.6
        ]
      },
      {
        "name": "rug_pink",
        "at": [
          8,
          10.4
        ],
        "collide": false
      },
      {
        "name": "lamp_red",
        "at": [
          18,
          7.6
        ]
      },
      {
        "name": "plant_pot",
        "at": [
          1.2,
          12
        ]
      }
    ],
    "seats": [
      {
        "at": [
          2.8,
          3.4
        ],
        "side": "right",
        "kind": "bed"
      },
      {
        "at": [
          6.8,
          3.4
        ],
        "side": "right",
        "kind": "bed"
      },
      {
        "at": [
          12.8,
          3.4
        ],
        "side": "left",
        "kind": "bed"
      },
      {
        "at": [
          16.8,
          3.4
        ],
        "side": "left",
        "kind": "bed"
      },
      {
        "at": [
          7.7,
          9.6
        ],
        "side": "right",
        "kind": "chair"
      },
      {
        "at": [
          12.5,
          9.6
        ],
        "side": "left",
        "kind": "chair"
      },
      {
        "at": [
          3.5,
          13.2
        ],
        "side": "right",
        "kind": "chair"
      }
    ],
    "animated": [
      {
        "name": "tv_news",
        "at": [
          9,
          0.4
        ]
      }
    ],
    "spawns": [
      [
        9.8,
        12.8
      ]
    ],
    "doors": [
      {
        "name": "exit",
        "at": [
          9.5,
          14
        ],
        "targetVenue": "district"
      }
    ],
    "glows": [],
    "id": "house_6",
    "label": "House 6"
  },
  {
    "archetype": "house",
    "indoor": true,
    "sizeTiles": [
      20,
      15
    ],
    "groundAtlas": "interiors_ground",
    "capacity": 7,
    "roles": [
      "home"
    ],
    "affords": [
      "sleep",
      "idle"
    ],
    "hours": [
      {
        "open": 0,
        "close": 24
      }
    ],
    "ground": {
      "wallA": "wallDormA",
      "wallB": "wallDormB",
      "floor": "floorDorm"
    },
    "furniture": [
      {
        "name": "bed_green",
        "at": [
          2,
          1.6
        ]
      },
      {
        "name": "bed_blue",
        "at": [
          6,
          1.6
        ]
      },
      {
        "name": "bed_teal",
        "at": [
          12,
          1.6
        ]
      },
      {
        "name": "bed_green",
        "at": [
          16,
          1.6
        ]
      },
      {
        "name": "nightstand",
        "at": [
          4.3,
          2.4
        ]
      },
      {
        "name": "nightstand",
        "at": [
          14.3,
          2.4
        ]
      },
      {
        "name": "table_plain",
        "at": [
          8.5,
          7.5
        ]
      },
      {
        "name": "chair_red_r",
        "at": [
          6.9,
          7.8
        ],
        "collide": false
      },
      {
        "name": "chair_red_l",
        "at": [
          11.7,
          7.8
        ],
        "collide": false
      },
      {
        "name": "armchair_grey_r",
        "at": [
          2.6,
          10.6
        ]
      },
      {
        "name": "rug_pink",
        "at": [
          8,
          10.4
        ],
        "collide": false
      },
      {
        "name": "lamp_red",
        "at": [
          18,
          7.6
        ]
      },
      {
        "name": "plant_pot",
        "at": [
          1.2,
          12
        ]
      }
    ],
    "seats": [
      {
        "at": [
          2.8,
          3.4
        ],
        "side": "right",
        "kind": "bed"
      },
      {
        "at": [
          6.8,
          3.4
        ],
        "side": "right",
        "kind": "bed"
      },
      {
        "at": [
          12.8,
          3.4
        ],
        "side": "left",
        "kind": "bed"
      },
      {
        "at": [
          16.8,
          3.4
        ],
        "side": "left",
        "kind": "bed"
      },
      {
        "at": [
          7.7,
          9.6
        ],
        "side": "right",
        "kind": "chair"
      },
      {
        "at": [
          12.5,
          9.6
        ],
        "side": "left",
        "kind": "chair"
      },
      {
        "at": [
          3.5,
          13.2
        ],
        "side": "right",
        "kind": "chair"
      }
    ],
    "animated": [
      {
        "name": "tv_news",
        "at": [
          9,
          0.4
        ]
      }
    ],
    "spawns": [
      [
        9.8,
        12.8
      ]
    ],
    "doors": [
      {
        "name": "exit",
        "at": [
          9.5,
          14
        ],
        "targetVenue": "district"
      }
    ],
    "glows": [],
    "id": "house_7",
    "label": "House 7"
  },
  {
    "archetype": "house",
    "indoor": true,
    "sizeTiles": [
      20,
      15
    ],
    "groundAtlas": "interiors_ground",
    "capacity": 7,
    "roles": [
      "home"
    ],
    "affords": [
      "sleep",
      "idle"
    ],
    "hours": [
      {
        "open": 0,
        "close": 24
      }
    ],
    "ground": {
      "wallA": "wallDormA",
      "wallB": "wallDormB",
      "floor": "floorDorm"
    },
    "furniture": [
      {
        "name": "bed_green",
        "at": [
          2,
          1.6
        ]
      },
      {
        "name": "bed_blue",
        "at": [
          6,
          1.6
        ]
      },
      {
        "name": "bed_teal",
        "at": [
          12,
          1.6
        ]
      },
      {
        "name": "bed_green",
        "at": [
          16,
          1.6
        ]
      },
      {
        "name": "nightstand",
        "at": [
          4.3,
          2.4
        ]
      },
      {
        "name": "nightstand",
        "at": [
          14.3,
          2.4
        ]
      },
      {
        "name": "table_plain",
        "at": [
          8.5,
          7.5
        ]
      },
      {
        "name": "chair_red_r",
        "at": [
          6.9,
          7.8
        ],
        "collide": false
      },
      {
        "name": "chair_red_l",
        "at": [
          11.7,
          7.8
        ],
        "collide": false
      },
      {
        "name": "armchair_grey_r",
        "at": [
          2.6,
          10.6
        ]
      },
      {
        "name": "rug_pink",
        "at": [
          8,
          10.4
        ],
        "collide": false
      },
      {
        "name": "lamp_red",
        "at": [
          18,
          7.6
        ]
      },
      {
        "name": "plant_pot",
        "at": [
          1.2,
          12
        ]
      }
    ],
    "seats": [
      {
        "at": [
          2.8,
          3.4
        ],
        "side": "right",
        "kind": "bed"
      },
      {
        "at": [
          6.8,
          3.4
        ],
        "side": "right",
        "kind": "bed"
      },
      {
        "at": [
          12.8,
          3.4
        ],
        "side": "left",
        "kind": "bed"
      },
      {
        "at": [
          16.8,
          3.4
        ],
        "side": "left",
        "kind": "bed"
      },
      {
        "at": [
          7.7,
          9.6
        ],
        "side": "right",
        "kind": "chair"
      },
      {
        "at": [
          12.5,
          9.6
        ],
        "side": "left",
        "kind": "chair"
      },
      {
        "at": [
          3.5,
          13.2
        ],
        "side": "right",
        "kind": "chair"
      }
    ],
    "animated": [
      {
        "name": "tv_news",
        "at": [
          9,
          0.4
        ]
      }
    ],
    "spawns": [
      [
        9.8,
        12.8
      ]
    ],
    "doors": [
      {
        "name": "exit",
        "at": [
          9.5,
          14
        ],
        "targetVenue": "district"
      }
    ],
    "glows": [],
    "id": "house_8",
    "label": "House 8"
  },
  {
    "archetype": "house",
    "indoor": true,
    "sizeTiles": [
      20,
      15
    ],
    "groundAtlas": "interiors_ground",
    "capacity": 7,
    "roles": [
      "home"
    ],
    "affords": [
      "sleep",
      "idle"
    ],
    "hours": [
      {
        "open": 0,
        "close": 24
      }
    ],
    "ground": {
      "wallA": "wallDormA",
      "wallB": "wallDormB",
      "floor": "floorDorm"
    },
    "furniture": [
      {
        "name": "bed_green",
        "at": [
          2,
          1.6
        ]
      },
      {
        "name": "bed_blue",
        "at": [
          6,
          1.6
        ]
      },
      {
        "name": "bed_teal",
        "at": [
          12,
          1.6
        ]
      },
      {
        "name": "bed_green",
        "at": [
          16,
          1.6
        ]
      },
      {
        "name": "nightstand",
        "at": [
          4.3,
          2.4
        ]
      },
      {
        "name": "nightstand",
        "at": [
          14.3,
          2.4
        ]
      },
      {
        "name": "table_plain",
        "at": [
          8.5,
          7.5
        ]
      },
      {
        "name": "chair_red_r",
        "at": [
          6.9,
          7.8
        ],
        "collide": false
      },
      {
        "name": "chair_red_l",
        "at": [
          11.7,
          7.8
        ],
        "collide": false
      },
      {
        "name": "armchair_grey_r",
        "at": [
          2.6,
          10.6
        ]
      },
      {
        "name": "rug_pink",
        "at": [
          8,
          10.4
        ],
        "collide": false
      },
      {
        "name": "lamp_red",
        "at": [
          18,
          7.6
        ]
      },
      {
        "name": "plant_pot",
        "at": [
          1.2,
          12
        ]
      }
    ],
    "seats": [
      {
        "at": [
          2.8,
          3.4
        ],
        "side": "right",
        "kind": "bed"
      },
      {
        "at": [
          6.8,
          3.4
        ],
        "side": "right",
        "kind": "bed"
      },
      {
        "at": [
          12.8,
          3.4
        ],
        "side": "left",
        "kind": "bed"
      },
      {
        "at": [
          16.8,
          3.4
        ],
        "side": "left",
        "kind": "bed"
      },
      {
        "at": [
          7.7,
          9.6
        ],
        "side": "right",
        "kind": "chair"
      },
      {
        "at": [
          12.5,
          9.6
        ],
        "side": "left",
        "kind": "chair"
      },
      {
        "at": [
          3.5,
          13.2
        ],
        "side": "right",
        "kind": "chair"
      }
    ],
    "animated": [
      {
        "name": "tv_news",
        "at": [
          9,
          0.4
        ]
      }
    ],
    "spawns": [
      [
        9.8,
        12.8
      ]
    ],
    "doors": [
      {
        "name": "exit",
        "at": [
          9.5,
          14
        ],
        "targetVenue": "district"
      }
    ],
    "glows": [],
    "id": "house_9",
    "label": "House 9"
  },
  {
    "id": "library",
    "label": "Library",
    "indoor": true,
    "sizeTiles": [
      20,
      15
    ],
    "groundAtlas": "interiors_ground",
    "capacity": 4,
    "roles": [
      "work",
      "hangout"
    ],
    "affords": [
      "read",
      "work",
      "idle"
    ],
    "hours": [
      {
        "open": 8,
        "close": 22
      }
    ],
    "ground": {
      "wallA": "wallLibA",
      "wallB": "wallLibB",
      "floor": "floorLib"
    },
    "furniture": [
      {
        "name": "bookshelf_a",
        "at": [
          1,
          0.7
        ]
      },
      {
        "name": "bookshelf_b",
        "at": [
          4,
          0.7
        ]
      },
      {
        "name": "bookshelf_a",
        "at": [
          7,
          0.7
        ]
      },
      {
        "name": "bookshelf_narrow",
        "at": [
          10,
          0.4
        ]
      },
      {
        "name": "bookshelf_b",
        "at": [
          11.5,
          0.7
        ]
      },
      {
        "name": "bookshelf_a",
        "at": [
          14.5,
          0.7
        ]
      },
      {
        "name": "chalkboard",
        "at": [
          17.6,
          0.4
        ],
        "collide": false
      },
      {
        "name": "lectern",
        "at": [
          9.4,
          4
        ]
      },
      {
        "name": "globe",
        "at": [
          1.4,
          5
        ]
      },
      {
        "name": "lamp_red",
        "at": [
          18,
          4.6
        ]
      },
      {
        "name": "table_plain",
        "at": [
          4,
          7.5
        ]
      },
      {
        "name": "chair_yellow_r",
        "at": [
          2.4,
          7.8
        ],
        "collide": false
      },
      {
        "name": "chair_yellow_l",
        "at": [
          7.2,
          7.8
        ],
        "collide": false
      },
      {
        "name": "table_plain",
        "at": [
          13,
          7.5
        ]
      },
      {
        "name": "chair_blue_r",
        "at": [
          11.4,
          7.8
        ],
        "collide": false
      },
      {
        "name": "chair_blue_l",
        "at": [
          16.2,
          7.8
        ],
        "collide": false
      },
      {
        "name": "plant_palm",
        "at": [
          1.2,
          10.5
        ]
      },
      {
        "name": "plant_pot",
        "at": [
          18,
          12
        ]
      }
    ],
    "seats": [
      {
        "at": [
          3.2,
          9.6
        ],
        "side": "right",
        "kind": "chair"
      },
      {
        "at": [
          8,
          9.6
        ],
        "side": "left",
        "kind": "chair"
      },
      {
        "at": [
          12.2,
          9.6
        ],
        "side": "right",
        "kind": "chair"
      },
      {
        "at": [
          17,
          9.6
        ],
        "side": "left",
        "kind": "chair"
      }
    ],
    "animated": [
      {
        "name": "cuckoo_clock",
        "at": [
          13,
          0.3
        ]
      }
    ],
    "spawns": [
      [
        9.8,
        12.8
      ]
    ],
    "doors": [
      {
        "name": "exit",
        "at": [
          9.5,
          14
        ],
        "targetVenue": "district"
      }
    ],
    "glows": []
  },
  {
    "id": "office",
    "label": "Office",
    "indoor": true,
    "sizeTiles": [
      20,
      15
    ],
    "groundAtlas": "interiors_ground",
    "capacity": 4,
    "roles": [
      "work"
    ],
    "affords": [
      "work"
    ],
    "hours": [
      {
        "open": 8,
        "close": 20
      }
    ],
    "ground": {
      "wallA": "wallOfficeA",
      "wallB": "wallOfficeB",
      "floor": "floorOffice"
    },
    "furniture": [
      {
        "name": "workstation_single",
        "at": [
          2,
          1.2
        ]
      },
      {
        "name": "workstation_double",
        "at": [
          6.5,
          1.2
        ]
      },
      {
        "name": "workstation_single",
        "at": [
          12,
          1.2
        ]
      },
      {
        "name": "whiteboard",
        "at": [
          15.5,
          0.2
        ],
        "collide": false
      },
      {
        "name": "printer",
        "at": [
          17.5,
          1.6
        ]
      },
      {
        "name": "coffee_machine",
        "at": [
          1.2,
          5.5
        ]
      },
      {
        "name": "plant_pot",
        "at": [
          18,
          5
        ]
      },
      {
        "name": "plant_small",
        "at": [
          1.2,
          12
        ]
      },
      {
        "name": "table_plain",
        "at": [
          7,
          6.5
        ]
      },
      {
        "name": "table_plain",
        "at": [
          10,
          6.5
        ]
      },
      {
        "name": "chair_blue_r",
        "at": [
          5.4,
          6.8
        ],
        "collide": false
      },
      {
        "name": "chair_blue_r",
        "at": [
          5.4,
          8.3
        ],
        "collide": false
      },
      {
        "name": "chair_blue_l",
        "at": [
          13.2,
          6.8
        ],
        "collide": false
      },
      {
        "name": "chair_blue_l",
        "at": [
          13.2,
          8.3
        ],
        "collide": false
      },
      {
        "name": "plant_palm",
        "at": [
          17.5,
          10.5
        ]
      }
    ],
    "seats": [
      {
        "at": [
          6.2,
          8.6
        ],
        "side": "right",
        "kind": "chair"
      },
      {
        "at": [
          6.2,
          10.1
        ],
        "side": "right",
        "kind": "chair"
      },
      {
        "at": [
          14,
          8.6
        ],
        "side": "left",
        "kind": "chair"
      },
      {
        "at": [
          14,
          10.1
        ],
        "side": "left",
        "kind": "chair"
      }
    ],
    "animated": [
      {
        "name": "office_screen",
        "at": [
          4.5,
          0.3
        ]
      },
      {
        "name": "coffee_steam",
        "at": [
          1.5,
          4.6
        ]
      }
    ],
    "spawns": [
      [
        9.8,
        12.5
      ]
    ],
    "doors": [
      {
        "name": "exit",
        "at": [
          9.5,
          14
        ],
        "targetVenue": "district"
      }
    ],
    "glows": []
  }
];
